

##GitHub is flexible with however you want to name your workflow file, 
## but the file has to be a yaml file and it has to be in the .github/workflows folder.
name: cd

on:
  push:
    branches:
      - 'master'

jobs:
## Builds a Docker image and Pushes it to Docker Hub 
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build -t front .
      - name: Docker Image Tagging
        run: |
          docker tag front ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker tag front ${{ secrets.DOCKER_USER }}/front:latest
      - name: Docker Image Pushing
        run: |
          docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/front:latest