##A project can have multiple workflow files like build, release, etc, 
##but for the sake of simplicity, we’ll be using only one file for this project.


##GitHub is flexible with however you want to name your workflow file, 
## but the file has to be a yaml file and it has to be in the .github/workflows folder.
name: main


## A workflow trigger is required for a workflow. 
## I configured the workflow to trigger on pushes to the master branch
on:
  push:
    branches:
      - 'master'

## In order to reduce build time and build complexity,
## I will keep as much work inside one job as possible.
## Job below is created to build and test the Angular application

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps: 

            ## Since jobs do not pull down the source code by default,
            ## you need to explicitly tell the job to do so
          - name: Checkout
            uses: actions/checkout@v1    


            ## To setup Node.js used by the job
          - name: Use Node 12.x
            uses: actions/setup-node@v1
            with:
              node-version: '12.x'


          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build:ci
          - name: run on linux
              if: startsWith(matrix.os,'ubuntu')
              run: |
                npm run test-headless
          - name: Test
            run: npm run test:ci
          - name: Archive build
            if: success()
            uses: actions/upload-artifact@v1
            with:
              name: deploy_dist
              path: dist
          - name: Archive code coverage result
            if: success()
            uses: actions/upload-artifact@v1
            with:
              name: deploy_coverage
              path: coverage
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      
      ##Push Build to Releases
      - name: Deploy to GitHub Pages
        uses: sagun786/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/sagun786